services:
  # --- API-GW ---
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: oregon-jaeger
    ports:
      - "16686:16686"
      - "16687:16687"
      - "4317:4317"
      - "4318:4318"

  oregon-api-gw:
    image: ghcr.io/oregon-mai/oregon-api-gateway:latest
    ports:
      - "8000:8000"
    volumes:
      - ./configs/api-gw.yml:/app/config/local.yml:ro
      - ./logs/:/app/logs/
    depends_on:
      jaeger:
        condition: service_started

  # ------

  # --- Resource service ---
  oregon-resource-service:
    image: ghcr.io/oregon-mai/oregon-resource-service:latest
    container_name: oregon-resource-service
    volumes:
      - ./configs/resource.yaml:/app/config/local.yml:ro
    depends_on:
      postgres-resource-service:
        condition: service_healthy
    ports:
      - "60008:60008"
      - "60009:60009"
    restart: on-failure

  postgres-resource-service:
    image: postgres:16-alpine
    container_name: oregon-resource-postgres
    environment:
      POSTGRES_DB: resource_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata-resource:/var/lib/postgresql/data
      - ./migrations/0001_resources.sql:/docker-entrypoint-initdb.d/0001_resources.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
  # ------

  # --- SSO ---
  postgres-sso-service:
    image: postgres:16-alpine
    container_name: postgres-sso-service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - pgdata-sso:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    command: ["postgres", "-p", "5433"]

  sso-service:
    image: ghcr.io/oregon-mai/oregon_sso_service:latest
    container_name: oregon-sso
    environment:
      - JAEGER=jaeger:4317
    ports:
      - "8001:8001"
    depends_on:
      - postgres-sso-service
      - jaeger

  # --- Booking ----
  oregon-booking-service:
    image: ghcr.io/oregon-mai/oregon-booking-service:latest
    volumes:
      - ./configs/booking.yaml:/app/config/local.yml:ro
    depends_on:
      booking-postgres:
        condition: service_healthy
      oregon-resource-service:
        condition: service_started
      kafka-init-topics:
        condition: service_completed_successfully
      jaeger:
        condition: service_started
    ports:
      - "60017:60017"
    restart: on-failure

  booking-postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: booking_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5438:5432"
    volumes:
      - pgdata-booking:/var/lib/postgresql/data
      - ./migrations/0001_bookings.sql:/docker-entrypoint-initdb.d/0001_bookings.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d booking_service"]
      interval: 5s
      timeout: 3s
      retries: 20
  # ------

  # --- Notification ---
  oregon-notification-service:
    image: ghcr.io/oregon-mai/oregon-notification-service:latest
    restart: on-failure
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - TOPICS=topic.user.booking,topic.user.cancel,topic.admin.cancel,admin.update,messages
      - DATABASE_URL=postgresql+asyncpg://postgres:root@notification-postgres:5432/postgres
    ports:
      - "8003:8003"
    depends_on:
      kafka:
        condition: service_healthy
      notification-postgres:
        condition: service_healthy

  notification-postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    volumes:
      - pgdata-notification:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 20
  # ------

  # --- Kafka ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      zookeeper:
        condition: service_started
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "kafka-topics --bootstrap-server localhost:9092 --list > /dev/null 2>&1",
        ]
      interval: 5s
      timeout: 5s
      retries: 20

  kafbat-ui:
    image: kafbat/kafka-ui:latest
    container_name: oregon-kafbat-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "oregon-kafka"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:29092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"
      KAFKA_CLUSTERS_0_METRICS_PORT: 9092
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_CLUSTERS_0_POLLING_TIMEOUT_MS: 5000
      DYNAMIC_CONFIG_ENABLED: "false"
      SWAGGER_UI_ENABLED: "true"
    depends_on:
      kafka:
        condition: service_healthy
      zookeeper:
        condition: service_started
    restart: on-failure

  kafka-init-topics:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-ec"]
    command:
      - >-
        cub kafka-ready -b kafka:29092 1 60;
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic topic.user.booking --replication-factor 1 --partitions 3;
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic topic.admin.cancel --replication-factor 1 --partitions 3;
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic topic.user.cancel --replication-factor 1 --partitions 3;
        kafka-topics --bootstrap-server kafka:29092 --list
    restart: "no"

volumes:
  pgdata-resource:
  pgdata-sso:
  pgdata-booking:
  pgdata-notification:
