include:
  - devops/docker-compose.api-gw.yml
  - devops/docker-compose.resource.yml
  - devops/docker-compose.sso.yml
  - devops/docker-compose.booking.yml
  - devops/docker-compose.notification.yml
  - devops/docker-compose.kafka.yml
  - devops/docker-compose.grafana.yml
