services:
  # --- API-GW ---
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: oregon-jaeger
    ports:
      - "16686:16686"
      - "16687:16687"
      - "4317:4317"
      - "4318:4318"

  envoy:
    image: envoyproxy/envoy:v1.38.0
    container_name: oregon-envoy
    ports:
      - "8000:10000"
      - "9901:9901"
    volumes:
      - ./configs/envoy.yaml:/etc/envoy/envoy.yaml:ro
    depends_on:
      - oregon-api-gw

  oregon-api-gw:
    image: ghcr.io/oregon-mai/oregon-api-gateway:latest
    deploy:
      replicas: 3
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./configs/api-gw.yml:/app/config/local.yml:ro
      - ./logs/:/app/logs/
    depends_on:
      jaeger:
        condition: service_started

  # ------

  # --- Resource service ---
  oregon-resource-service:
    image: ghcr.io/oregon-mai/oregon-resource-service:latest
    container_name: oregon-resource-service
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./configs/resource.yaml:/app/config/local.yml:ro
    depends_on:
      postgres-resource-service:
        condition: service_healthy
    restart: on-failure

  postgres-resource-service:
    image: postgres:16-alpine
    container_name: oregon-resource-postgres
    environment:
      TZ: Europe/Moscow
      POSTGRES_DB: resource_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata-resource:/var/lib/postgresql/data
      - ./migrations/0001_resources.sql:/docker-entrypoint-initdb.d/0001_resources.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
  # ------

  # --- SSO ---
  postgres-sso-service:
    image: postgres:16-alpine
    container_name: postgres-sso-service
    environment:
      TZ: Europe/Moscow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - pgdata-sso:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    command: ["postgres", "-p", "5433"]

  sso-service:
    image: ghcr.io/oregon-mai/oregon_sso_service:latest
    container_name: oregon-sso
    environment:
      - JAEGER=jaeger:4317
      - TZ=Europe/Moscow
    depends_on:
      - postgres-sso-service
      - jaeger

  # --- Booking ----
  oregon-booking-service:
    image: ghcr.io/oregon-mai/oregon-booking-service:latest
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./configs/booking.yaml:/app/config/local.yml:ro
    depends_on:
      booking-postgres:
        condition: service_healthy
      oregon-resource-service:
        condition: service_started
      kafka-init-topics:
        condition: service_completed_successfully
      jaeger:
        condition: service_started
    restart: on-failure

  booking-postgres:
    image: postgres:16-alpine
    environment:
      TZ: Europe/Moscow
      POSTGRES_DB: booking_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata-booking:/var/lib/postgresql/data
      - ./migrations/0001_bookings.sql:/docker-entrypoint-initdb.d/0001_bookings.sql:ro
      - ./migrations/0002_outbox.sql:/docker-entrypoint-initdb.d/0002_outbox.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d booking_service"]
      interval: 5s
      timeout: 3s
      retries: 20
  # ------

  # --- Notification ---
  oregon-notification-service:
    image: ghcr.io/oregon-mai/oregon-notification-service:latest
    restart: on-failure
    environment:
      - TZ=Europe/Moscow
      - REDIS_PASS=redispass
      - REDIS_URL=notification-redis
      - REDIS_PORT=6379
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - USER_BOOK_TOPIC=topic.user.booking
      - USER_CANCEL_TOPIC=topic.user.cancel
      - ADMIN_CANCEL_TOPIC=topic.admin.cancel
      - ADMIN_UPDATE_TOPIC=admin.update
      - MESSAGES_TOPIC=messages
    depends_on:
      kafka:
        condition: service_healthy
      notification-redis:
        condition: service_healthy

  notification-redis:
    image: redis:7.4-bookworm
    environment:
      - TZ=Europe/Moscow
    volumes:
      - redisdata-notification:/data
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --requirepass "redispass"
      --maxmemory-policy allkeys-lru
      --save ""
      --tcp-backlog 511
      --timeout 300
      --tcp-keepalive 300
      --databases 16
      --stop-writes-on-bgsave-error no
      --repl-diskless-sync no
    restart: on-failure
    sysctls:
      - net.core.somaxconn=512
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redispass", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  # ------

  # --- Kafka ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      TZ: Europe/Moscow
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      zookeeper:
        condition: service_started
    ports:
      - "9092:9092"
    environment:
      TZ: Europe/Moscow
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "kafka-topics --bootstrap-server localhost:9092 --list > /dev/null 2>&1",
        ]
      interval: 5s
      timeout: 5s
      retries: 20

  kafbat-ui:
    image: kafbat/kafka-ui:latest
    container_name: oregon-kafbat-ui
    ports:
      - "8080:8080"
    environment:
      TZ: Europe/Moscow
      KAFKA_CLUSTERS_0_NAME: "oregon-kafka"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:29092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"
      KAFKA_CLUSTERS_0_METRICS_PORT: 9092
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_CLUSTERS_0_POLLING_TIMEOUT_MS: 5000
      DYNAMIC_CONFIG_ENABLED: "false"
      SWAGGER_UI_ENABLED: "true"
    depends_on:
      kafka:
        condition: service_healthy
      zookeeper:
        condition: service_started
    restart: on-failure

  kafka-init-topics:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-ec"]
    command:
      - >-
        cub kafka-ready -b kafka:29092 1 60;
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic topic.user.booking --replication-factor 1 --partitions 3;
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic topic.admin.cancel --replication-factor 1 --partitions 3;
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic topic.user.cancel --replication-factor 1 --partitions 3;
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic topic.messages.start --replication-factor 1 --partitions 3;
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic topic.messages.end --replication-factor 1 --partitions 3;
        kafka-topics --bootstrap-server kafka:29092 --list
    restart: "no"

volumes:
  pgdata-resource:
  pgdata-sso:
  pgdata-booking:
  redisdata-notification:
