global:
  scrape_interval: 15s

scrape_configs:
  - job_name: api-gateway
    static_configs:
      - targets:
          - oregon-api-gw:8000
        labels:
          env: compose
  - job_name: sso-service
    static_configs:
      - targets:
          - oregon-sso-service:8001
        labels:
          env: compose
  - job_name: booking-service
    static_configs:
      - targets:
          - oregon-booking-service:9097
  - job_name: resource-service
    static_configs:
      - targets:
          - oregon-resource-service:9098
        labels:
          env: compose
