scrape_configs:
  - job_name: api-gateway
    static_configs:
      - targets:
          - oregon-api-gw:8000
        labels:
          env: compose
  - job_name: sso-service
    static_configs:
      - targets:
          - oregon-sso-service:8001
        labels:
          env: compose
